-- Migração: Criação da estrutura do banco de dados para o chatbot IA (n8n)
-- O prefixo "ia_suporte_" foi adotado para todas as tabelas.
-- Tipos de dados de texto utilizados conforme instrução para as colunas não numéricas e não booleanas.

-- 1. Criação da tabela de Usuários
CREATE TABLE public.ia_suporte_usuarios (
    telefone TEXT PRIMARY KEY, -- Definido como PK conforme a instrução
    uuid TEXT NOT NULL,
    nome TEXT,
    data_de_criacao TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 2. Criação da tabela de Atendimentos
CREATE TABLE public.ia_suporte_atendimentos (
    id_atendimento TEXT PRIMARY KEY, -- ID gerado pelo bot, definido como PK
    uuid TEXT NOT NULL,
    telefone_usuario TEXT NOT NULL,
    em_atendimento BOOLEAN DEFAULT TRUE,
    demanda TEXT,
    criada_em TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_usuario FOREIGN KEY (telefone_usuario) REFERENCES public.ia_suporte_usuarios(telefone) ON DELETE CASCADE
);

-- 3. Criação da tabela de Mensagens
CREATE TABLE public.ia_suporte_mensagens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- PK recomendada para organizar cada mensagem individualmente
    texto_da_mensagem TEXT NOT NULL,
    id_atendimento TEXT NOT NULL,
    criada_em TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP, -- Adicionado para manter um histórico temporal das mensagens
    CONSTRAINT fk_atendimento FOREIGN KEY (id_atendimento) REFERENCES public.ia_suporte_atendimentos(id_atendimento) ON DELETE CASCADE
);

-- Adicionando índices para otimizar futuras consultas (robusteza e coletas de dados)
CREATE INDEX idx_ia_suporte_atendimentos_telefone ON public.ia_suporte_atendimentos(telefone_usuario);
CREATE INDEX idx_ia_suporte_mensagens_id_atendimento ON public.ia_suporte_mensagens(id_atendimento);
